# Generated by Django 4.1 on 2023-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_created_product_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', 'created')},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('order', 'created')},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
