# Generated by Django 4.1 on 2023-09-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_description_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-order', 'created')},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-is_primary',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-order', 'created')},
        ),
        migrations.AlterField(
            model_name='image',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
