# Generated by Django 4.1 on 2023-09-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_options_product_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
