# Generated by Django 4.1 on 2023-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_category_cover_alter_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contacts',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
