# Generated by Django 4.1 on 2023-09-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductParamater',
            new_name='ProductParameter',
        ),
    ]
