# Generated by Django 4.1 on 2023-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.TextField(),
        ),
    ]
